// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Prayer struct {
	ID          uuid.UUID
	Title       string
	Description string
	AuthorName  *string
	IsAnonymous bool
	Status      int32
	CreatedAt   time.Time
	CreatedBy   *uuid.UUID
	UpdatedAt   time.Time
	UpdatedBy   *uuid.UUID
	DeletedAt   *time.Time
	DeletedBy   *uuid.UUID
}
