// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const count = `-- name: Count :one
SELECt count(*) FROM prayers WHERE (
    $1::TEXT = ''
    OR title ILIKE ('%' || $1 || '%')
    OR description ILIKE ('%' || $1 || '%')
    OR author_name ILIKE ('%' || $1 || '%')
)
`

func (q *Queries) Count(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, count, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayer = `-- name: CreatePayer :one
INSERT INTO prayers (
    id,
    title,
    description,
    author_name,
    is_anonymous,
    status,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, title, description, author_name, is_anonymous, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreatePayerParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	AuthorName  *string
	IsAnonymous bool
	Status      int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreatePayer(ctx context.Context, arg CreatePayerParams) (Prayer, error) {
	row := q.db.QueryRow(ctx, createPayer,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AuthorName,
		arg.IsAnonymous,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Prayer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorName,
		&i.IsAnonymous,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const deletePrayer = `-- name: DeletePrayer :exec
DELETE FROM prayers WHERE id = $1
`

func (q *Queries) DeletePrayer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePrayer, id)
	return err
}

const getPrayerByID = `-- name: GetPrayerByID :one
SELECT id, title, description, author_name, is_anonymous, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM prayers WHERE id = $1
`

func (q *Queries) GetPrayerByID(ctx context.Context, id uuid.UUID) (Prayer, error) {
	row := q.db.QueryRow(ctx, getPrayerByID, id)
	var i Prayer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorName,
		&i.IsAnonymous,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listPrayers = `-- name: ListPrayers :many
SELECt id, title, description, author_name, is_anonymous, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM prayers WHERE (
    $1::TEXT = ''
    OR title ILIKE ('%' || $1 || '%')
    OR description ILIKE ('%' || $1 || '%')
    OR author_name ILIKE ('%' || $1 || '%')
) ORDER BY created_at DESC 
LIMIT $3 OFFSET $2
`

type ListPrayersParams struct {
	Search    string
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListPrayers(ctx context.Context, arg ListPrayersParams) ([]Prayer, error) {
	rows, err := q.db.Query(ctx, listPrayers, arg.Search, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prayer
	for rows.Next() {
		var i Prayer
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.AuthorName,
			&i.IsAnonymous,
			&i.Status,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrayer = `-- name: UpdatePrayer :one
UPDATE prayers SET 
    title = $2,
    description = $3,
    author_name = $4,
    is_anonymous = $5,
    status = $6,
    updated_at = NOW(),
    updated_by = $7
WHERE id = $1
RETURNING id, title, description, author_name, is_anonymous, status, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdatePrayerParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	AuthorName  *string
	IsAnonymous bool
	Status      int32
	UpdatedBy   *uuid.UUID
}

func (q *Queries) UpdatePrayer(ctx context.Context, arg UpdatePrayerParams) (Prayer, error) {
	row := q.db.QueryRow(ctx, updatePrayer,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.AuthorName,
		arg.IsAnonymous,
		arg.Status,
		arg.UpdatedBy,
	)
	var i Prayer
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.AuthorName,
		&i.IsAnonymous,
		&i.Status,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
