// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Member struct {
	ID          uuid.UUID
	FirstName   string
	LastName    string
	Email       *string
	Phone       *string
	Gender      int16
	Status      int16
	BirthDate   *time.Time
	BaptismDate *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Address     *string
	DeletedAt   *time.Time
	CreatedBy   *uuid.UUID
	UpdatedBy   *uuid.UUID
	DeletedBy   *uuid.UUID
}
