// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM members
WHERE (
    $1::text = ''
    OR first_name ILIKE ('%' || $1 || '%')
    OR last_name ILIKE ('%' || $1 || '%')
    OR email ILIKE ('%' || $1 || '%')
)
`

func (q *Queries) CountMembers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (first_name, last_name, email, phone, gender, address, birth_date, baptism_date, status) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, first_name, last_name, email, phone, gender, status, birth_date, baptism_date, created_at, updated_at, address, deleted_at, created_by, updated_by, deleted_by
`

type CreateMemberParams struct {
	FirstName   string
	LastName    string
	Email       *string
	Phone       *string
	Gender      string
	Address     *string
	BirthDate   *time.Time
	BaptismDate *time.Time
	Status      string
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Gender,
		arg.Address,
		arg.BirthDate,
		arg.BaptismDate,
		arg.Status,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Gender,
		&i.Status,
		&i.BirthDate,
		&i.BaptismDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Address,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMember, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, first_name, last_name, email, phone, gender, status, birth_date, baptism_date, created_at, updated_at, address, deleted_at, created_by, updated_by, deleted_by FROM members WHERE id = $1
`

func (q *Queries) GetMemberByID(ctx context.Context, id uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Gender,
		&i.Status,
		&i.BirthDate,
		&i.BaptismDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Address,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT id, first_name, last_name, email, phone, gender, status, birth_date, baptism_date, created_at, updated_at, address, deleted_at, created_by, updated_by, deleted_by FROM members WHERE (
    $1::TEXT = ''
    OR first_name ILIKE ('%' || $1 || '%')
    OR last_name ILIKE ('%' || $1 || '%')
    OR email ILIKE ('%' || $1 || '%')
) ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListMembersParams struct {
	Search    string
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.Search, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Gender,
			&i.Status,
			&i.BirthDate,
			&i.BaptismDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Address,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE members SET 
    first_name = $2,
    last_name = $3,
    email = $4,
    phone = $5,
    gender = $6,
    address = $7,
    birth_date = $8,
    baptism_date = $9,
    status = $10,
    updated_at = NOW()
WHERE id = $1 
RETURNING id, first_name, last_name, email, phone, gender, status, birth_date, baptism_date, created_at, updated_at, address, deleted_at, created_by, updated_by, deleted_by
`

type UpdateMemberParams struct {
	ID          uuid.UUID
	FirstName   string
	LastName    string
	Email       *string
	Phone       *string
	Gender      string
	Address     *string
	BirthDate   *time.Time
	BaptismDate *time.Time
	Status      string
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Gender,
		arg.Address,
		arg.BirthDate,
		arg.BaptismDate,
		arg.Status,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Gender,
		&i.Status,
		&i.BirthDate,
		&i.BaptismDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Address,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.DeletedBy,
	)
	return i, err
}
