// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products
WHERE (
    $1::text = ''
    OR name ILIKE '%' || $1 || '%'
    OR sku  ILIKE '%' || $1 || '%'
)
`

func (q *Queries) CountProducts(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, sku, description, brand, release_date, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, sku, description, brand, release_date, status, created_at, updated_at
`

type CreateProductParams struct {
	Name        string
	Sku         string
	Description *string
	Brand       *string
	ReleaseDate *time.Time
	Status      string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Sku,
		arg.Description,
		arg.Brand,
		arg.ReleaseDate,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Description,
		&i.Brand,
		&i.ReleaseDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :execrows
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, sku, description, brand, release_date, status, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Description,
		&i.Brand,
		&i.ReleaseDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, sku, description, brand, release_date, status, created_at, updated_at FROM products
WHERE (
    $1::text = ''
    OR name ILIKE '%' || $1 || '%'
    OR sku  ILIKE '%' || $1 || '%'
)
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListProductsParams struct {
	Search    string
	RowOffset int32
	RowLimit  int32
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Search, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Sku,
			&i.Description,
			&i.Brand,
			&i.ReleaseDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products SET
    name = $2, sku = $3, description = $4, brand = $5,
    release_date = $6, status = $7, updated_at = now()
WHERE id = $1
RETURNING id, name, sku, description, brand, release_date, status, created_at, updated_at
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Sku         string
	Description *string
	Brand       *string
	ReleaseDate *time.Time
	Status      string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Sku,
		arg.Description,
		arg.Brand,
		arg.ReleaseDate,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Sku,
		&i.Description,
		&i.Brand,
		&i.ReleaseDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
